### ISSUE TITLE
Proto namespace conflict

### ISSUE THREAD

**Issue by weeco** [connectrpc/authn-go#10]
Hey,
I tried to use authn-go today but noticed it wouldn't compile as soon as import the library in the code because of a namespace conflict. This is probably due to using different versions of the connect dependencies:

```
panic: proto: file "connectext/grpc/status/v1/status.proto" is already registered
        previously from: "connectrpc.com/connect/internal/gen/connectext/grpc/status/v1"
        currently from:  "github.com/bufbuild/connect-go/internal/gen/connectext/grpc/status/v1"
See https://protobuf.dev/reference/go/faq#namespace-conflict


goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1({0x105bb5a80, 0x14000158a80}, {0x105ba7f40, 0x14000051530})
        /Users/martinschneppenheim/go/pkg/mod/google.golang.org/protobuf@v1.32.0/reflect/protoregistry/registry.go:56 +0x528
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0x1400000e228, {0x105bc3468, 0x14000158a80})
        /Users/martinschneppenheim/go/pkg/mod/google.golang.org/protobuf@v1.32.0/reflect/protoregistry/registry.go:130 +0x464
google.golang.org/protobuf/internal/filedesc.Builder.Build({{0x1059dff11, 0x45}, {0x106227c80, 0x191, 0x191}, 0x0, 0x1, 0x0, 0x0, {0x105baae70, ...}, ...})
        /Users/martinschneppenheim/go/pkg/mod/google.golang.org/protobuf@v1.32.0/internal/filedesc/build.go:112 +0x1f0
google.golang.org/protobuf/internal/filetype.Builder.Build({{{0x1059dff11, 0x45}, {0x106227c80, 0x191, 0x191}, 0x0, 0x1, 0x0, 0x0, {0x0, ...}, ...}, ...})
        /Users/martinschneppenheim/go/pkg/mod/google.golang.org/protobuf@v1.32.0/internal/filetype/build.go:138 +0x1bc
github.com/bufbuild/connect-go/internal/gen/connectext/grpc/status/v1.file_connectext_grpc_status_v1_status_proto_init()
        /Users/martinschneppenheim/go/pkg/mod/github.com/bufbuild/connect-go@v1.10.0/internal/gen/connectext/grpc/status/v1/status.pb.go:197 +0x150
github.com/bufbuild/connect-go/internal/gen/connectext/grpc/status/v1.init.0()
        /Users/martinschneppenheim/go/pkg/mod/github.com/bufbuild/connect-go@v1.10.0/internal/gen/connectext/grpc/status/v1/status.pb.go:165 +0x1c
Exiting.
```

My go.mod:

```
require (
	buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go v1.32.0-20231115204500-e097f827e652.1
	connectrpc.com/authn v0.1.0
	github.com/bufbuild/connect-go v1.10.0
	github.com/bufbuild/connect-grpcreflect-go v1.1.0
	github.com/bufbuild/protovalidate-go v0.5.0
	github.com/clerkinc/clerk-sdk-go v1.49.0
	github.com/go-viper/mapstructure/v2 v2.0.0-alpha.1
	github.com/golang-migrate/migrate/v4 v4.17.0
	github.com/jackc/pgerrcode v0.0.0-20220416144525-469b46aa5efa
	github.com/jackc/pgx-zap v0.0.0-20221202020421-94b1cb2f889f
	github.com/jackc/pgx/v5 v5.5.2
	github.com/knadh/koanf/parsers/yaml v0.1.0
	github.com/knadh/koanf/providers/env v0.1.0
	github.com/knadh/koanf/providers/file v0.1.0
	github.com/knadh/koanf/v2 v2.0.2
	github.com/prometheus/client_golang v1.18.0
	github.com/rs/xid v1.5.0
	go.uber.org/zap v1.26.0
	golang.org/x/net v0.20.0
	golang.org/x/sync v0.6.0
	google.golang.org/genproto/googleapis/api v0.0.0-20240125205218-1f4bbc51befe
	google.golang.org/genproto/googleapis/rpc v0.0.0-20240125205218-1f4bbc51befe
	google.golang.org/grpc v1.61.0
	google.golang.org/protobuf v1.32.0
)

require (
	connectrpc.com/connect v1.14.0 // indirect
	github.com/antlr4-go/antlr/v4 v4.13.0 // indirect
	github.com/beorn7/perks v1.0.1 // indirect
	github.com/cespare/xxhash/v2 v2.2.0 // indirect
	github.com/fsnotify/fsnotify v1.7.0 // indirect
	github.com/go-jose/go-jose/v3 v3.0.1 // indirect
	github.com/golang/protobuf v1.5.3 // indirect
	github.com/google/cel-go v0.19.0 // indirect
	github.com/hashicorp/errwrap v1.1.0 // indirect
	github.com/hashicorp/go-multierror v1.1.1 // indirect
	github.com/jackc/pgpassfile v1.0.0 // indirect
	github.com/jackc/pgservicefile v0.0.0-20231201235250-de7065d80cb9 // indirect
	github.com/jackc/puddle/v2 v2.2.1 // indirect
	github.com/knadh/koanf/maps v0.1.1 // indirect
	github.com/lib/pq v1.10.9 // indirect
	github.com/mitchellh/copystructure v1.2.0 // indirect
	github.com/mitchellh/reflectwalk v1.0.2 // indirect
	github.com/prometheus/client_model v0.5.0 // indirect
	github.com/prometheus/common v0.46.0 // indirect
	github.com/prometheus/procfs v0.12.0 // indirect
	github.com/stoewer/go-strcase v1.3.0 // indirect
	go.uber.org/atomic v1.11.0 // indirect
	go.uber.org/multierr v1.11.0 // indirect
	golang.org/x/crypto v0.18.0 // indirect
	golang.org/x/exp v0.0.0-20240119083558-1b970713d09a // indirect
	golang.org/x/sys v0.16.0 // indirect
	golang.org/x/text v0.14.0 // indirect
	google.golang.org/genproto v0.0.0-20240125205218-1f4bbc51befe // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
```

**Comment by weeco** [comment]
It seems a bunch of buf dependencies have been moved into a "connectrpc" organization on GitHub. So after updating the go modules for e.g. grpcreflect => connectrpc.com/grpcreflect the namespace conflict was gone
